using System;
using System.Collections.Generic;

namespace PromptBar
{
    public sealed class LanguageOption
    {
        public LanguageOption(string code, string name)
        {
            Code = code;
            Name = name;
        }

        public string Code { get; private set; }
        public string Name { get; private set; }

        public override string ToString()
        {
            return Name;
        }
    }

    public static class Localization
    {
        public const string DefaultLanguageCode = "en";

        private static readonly LanguageOption[] languages = new LanguageOption[]
        {
            new LanguageOption("en", "English"),
            new LanguageOption("ru", "Русский"),
            new LanguageOption("uz", "O'zbekcha"),
            new LanguageOption("es", "Español"),
            new LanguageOption("it", "Italiano"),
            new LanguageOption("fr", "Français"),
            new LanguageOption("pt", "Português"),
            new LanguageOption("kaa", "Qaraqalpaqsha"),
            new LanguageOption("tg", "Тоҷикӣ"),
            new LanguageOption("kk", "Қазақша"),
            new LanguageOption("be", "Беларуская"),
            new LanguageOption("ja", "日本語"),
            new LanguageOption("zh", "中文"),
            new LanguageOption("hi", "हिन्दी")
        };

        private static readonly Dictionary<string, Dictionary<string, string>> texts =
            new Dictionary<string, Dictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            { "en", new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
                {
                    { "SettingsWindowTitle", "PromptBar Settings" },
                    { "SettingsHeader", "Settings" },
                    { "GeneralSection", "General" },
                    { "LanguageLabel", "Language" },
                    { "ScriptSection", "Script" },
                    { "Import", "Import" },
                    { "Export", "Export" },
                    { "Copy", "Copy" },
                    { "Paste", "Paste" },
                    { "PlaybackSection", "Playback" },
                    { "SpeedLabel", "Speed" },
                    { "ScrollModeLabel", "Scroll mode" },
                    { "ScrollInfinite", "Infinite" },
                    { "ScrollStopAtEnd", "Stop at end" },
                    { "AppearanceSection", "Appearance" },
                    { "FontFamilyLabel", "Font family" },
                    { "FontSizeLabel", "Font size" },
                    { "OverlayWidthLabel", "Overlay width" },
                    { "OverlayHeightLabel", "Overlay height" },
                    { "DisplaySection", "Display" },
                    { "ShowOverlayOnLabel", "Show overlay on" },
                    { "ScreenAutoPrimary", "Auto (Primary screen)" },
                    { "ScreenPrimarySuffix", "Primary" },
                    { "PrivacySection", "Privacy" },
                    { "ShowOverlay", "Show overlay" },
                    { "LimitScreenSharingCapture", "Limit screen sharing capture" },
                    { "PrivacyNote", "Best effort only. Capture behavior can vary by Windows version and recording app." },
                    { "ShortcutsSection", "Keyboard Shortcuts" },
                    { "HotkeyHelp", "Hotkey Help" },
                    { "ResetDefaults", "Reset Defaults" },
                    { "HotkeyPressNew", "Press a new shortcut. Esc cancels, Backspace clears." },
                    { "HotkeyCleared", "Shortcut cleared." },
                    { "HotkeyUseModifier", "Use at least one modifier key: Ctrl, Alt, Shift, or Win." },
                    { "HotkeyAlreadyAssigned", "That shortcut is already assigned." },
                    { "HotkeyUpdated", "Shortcut updated." },
                    { "HotkeyPressKeys", "Press keys..." },
                    { "HotkeyDefaultsRestored", "Default shortcuts restored." },
                    { "ImportFailedTitle", "Import failed" },
                    { "ExportFailedTitle", "Export failed" },
                    { "OpenFileFilter", "Supported script files|*.txt;*.text;*.md;*.markdown;*.rtf;*.docx;*.csv;*.json;*.xml;*.yaml;*.yml;*.log|Text files|*.txt;*.text;*.md;*.markdown|Rich Text|*.rtf|Word documents|*.docx|All files|*.*" },
                    { "SaveFileFilter", "Text files|*.txt|Markdown|*.md|Rich Text|*.rtf|Word documents|*.docx|All files|*.*" },
                    { "ScriptDefault", "Paste your script here.\r\n\r\nTip: Use the tray icon to start/pause or reset the scroll." },
                    { "FontAppleDefault", "Apple / SF Pro (default)" },
                    { "FontGilroy", "Gilroy" },
                    { "FontSegoeVariable", "Segoe UI Variable" },
                    { "FontSegoe", "Segoe UI" },
                    { "FontArial", "Arial" },
                    { "Start", "Start" },
                    { "Pause", "Pause" },
                    { "StartPause", "Start / Pause" },
                    { "ResetScroll", "Reset scroll" },
                    { "JumpBack5s", "Jump back 5 seconds" },
                    { "TogglePrivacyMode", "Toggle privacy mode" },
                    { "ToggleOverlayVisibility", "Toggle overlay visibility" },
                    { "IncreaseSpeed", "Increase speed" },
                    { "DecreaseSpeed", "Decrease speed" },
                    { "IncreaseFontSize", "Increase font size" },
                    { "DecreaseFontSize", "Decrease font size" },
                    { "PrivacyMode", "Privacy Mode" },
                    { "ShowOverlayMenu", "Show Overlay" },
                    { "SettingsMenu", "Settings..." },
                    { "QuitPromptBar", "Quit PromptBar" },
                    { "ShortcutUnavailable", "Shortcut unavailable" },
                    { "ShortcutsUnavailable", "Shortcuts unavailable" },
                    { "HotkeyDialogTitle", "PromptBar Hotkeys" },
                    { "HotkeyUnassigned", "Unassigned" },
                    { "TextEditingShortcutsHeader", "Text editing" },
                    { "SelectAll", "Select all" },
                    { "NoScriptMessage", "No script yet.\r\nOpen Settings and paste your script to begin." },
                    { "ReadyMessage", "Ready to prompt.\r\nPress Start to begin." },
                    { "OverlayResize", "Resize overlay" },
                    { "OverlaySettings", "Settings" },
                    { "OverlayHotkeyHelp", "Hotkey help" },
                    { "OverlayPaste", "Paste script from clipboard" },
                    { "OverlayCopy", "Copy script to clipboard" },
                    { "OverlayClear", "Clear script" },
                    { "OverlayQuit", "Quit PromptBar" }
                }
            },
            { "ru", new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
                {
                    { "SettingsWindowTitle", "Настройки PromptBar" },
                    { "SettingsHeader", "Настройки" },
                    { "GeneralSection", "Общие" },
                    { "LanguageLabel", "Язык" },
                    { "ScriptSection", "Текст" },
                    { "Import", "Импорт" },
                    { "Export", "Экспорт" },
                    { "Copy", "Копировать" },
                    { "Paste", "Вставить" },
                    { "PlaybackSection", "Суфлёр" },
                    { "SpeedLabel", "Скорость" },
                    { "ScrollModeLabel", "Режим прокрутки" },
                    { "ScrollInfinite", "Бесконечно" },
                    { "ScrollStopAtEnd", "Остановить в конце" },
                    { "AppearanceSection", "Внешний вид" },
                    { "FontFamilyLabel", "Шрифт" },
                    { "FontSizeLabel", "Размер шрифта" },
                    { "OverlayWidthLabel", "Ширина overlay" },
                    { "OverlayHeightLabel", "Высота overlay" },
                    { "DisplaySection", "Экран" },
                    { "ShowOverlayOnLabel", "Показывать overlay на" },
                    { "ScreenAutoPrimary", "Авто (основной экран)" },
                    { "ScreenPrimarySuffix", "Основной" },
                    { "PrivacySection", "Приватность" },
                    { "ShowOverlay", "Показывать overlay" },
                    { "LimitScreenSharingCapture", "Скрывать при демонстрации экрана" },
                    { "PrivacyNote", "Работает по возможности. Захват может отличаться в разных версиях Windows и приложениях записи." },
                    { "ShortcutsSection", "Горячие клавиши" },
                    { "HotkeyHelp", "Подсказка по хоткеям" },
                    { "ResetDefaults", "Сбросить" },
                    { "HotkeyPressNew", "Нажмите новое сочетание. Esc отменяет, Backspace очищает." },
                    { "HotkeyCleared", "Сочетание очищено." },
                    { "HotkeyUseModifier", "Используйте хотя бы один модификатор: Ctrl, Alt, Shift или Win." },
                    { "HotkeyAlreadyAssigned", "Это сочетание уже назначено." },
                    { "HotkeyUpdated", "Сочетание обновлено." },
                    { "HotkeyPressKeys", "Нажмите клавиши..." },
                    { "HotkeyDefaultsRestored", "Стандартные сочетания восстановлены." },
                    { "ImportFailedTitle", "Импорт не удался" },
                    { "ExportFailedTitle", "Экспорт не удался" },
                    { "ScriptDefault", "Вставьте текст суфлёра здесь.\r\n\r\nПодсказка: используйте значок в трее, чтобы запустить, поставить на паузу или сбросить прокрутку." },
                    { "FontAppleDefault", "Apple / SF Pro (по умолчанию)" },
                    { "Start", "Старт" },
                    { "Pause", "Пауза" },
                    { "StartPause", "Старт / Пауза" },
                    { "ResetScroll", "Сброс прокрутки" },
                    { "JumpBack5s", "Назад на 5 секунд" },
                    { "TogglePrivacyMode", "Переключить приватность" },
                    { "ToggleOverlayVisibility", "Показать/скрыть overlay" },
                    { "IncreaseSpeed", "Увеличить скорость" },
                    { "DecreaseSpeed", "Уменьшить скорость" },
                    { "IncreaseFontSize", "Увеличить размер шрифта" },
                    { "DecreaseFontSize", "Уменьшить размер шрифта" },
                    { "PrivacyMode", "Приватный режим" },
                    { "ShowOverlayMenu", "Показывать overlay" },
                    { "SettingsMenu", "Настройки..." },
                    { "QuitPromptBar", "Выйти из PromptBar" },
                    { "ShortcutUnavailable", "Сочетание недоступно" },
                    { "ShortcutsUnavailable", "Недоступные сочетания" },
                    { "HotkeyDialogTitle", "Хоткеи PromptBar" },
                    { "HotkeyUnassigned", "Не назначено" },
                    { "TextEditingShortcutsHeader", "Редактирование текста" },
                    { "SelectAll", "Выделить всё" },
                    { "NoScriptMessage", "Текста пока нет.\r\nОткройте настройки и вставьте текст." },
                    { "ReadyMessage", "Готов к суфлёру.\r\nНажмите Старт, чтобы начать." },
                    { "OverlayResize", "Изменить размер overlay" },
                    { "OverlaySettings", "Настройки" },
                    { "OverlayHotkeyHelp", "Подсказка по хоткеям" },
                    { "OverlayPaste", "Вставить текст из буфера" },
                    { "OverlayCopy", "Копировать текст в буфер" },
                    { "OverlayClear", "Очистить текст" },
                    { "OverlayQuit", "Выйти из PromptBar" }
                }
            },
            { "uz", new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
                {
                    { "SettingsWindowTitle", "PromptBar sozlamalari" },
                    { "SettingsHeader", "Sozlamalar" },
                    { "GeneralSection", "Umumiy" },
                    { "LanguageLabel", "Til" },
                    { "ScriptSection", "Matn" },
                    { "Import", "Import" },
                    { "Export", "Eksport" },
                    { "Copy", "Nusxalash" },
                    { "Paste", "Qo'yish" },
                    { "PlaybackSection", "Suflyor" },
                    { "SpeedLabel", "Tezlik" },
                    { "ScrollModeLabel", "Prokrutka rejimi" },
                    { "ScrollInfinite", "Cheksiz" },
                    { "ScrollStopAtEnd", "Oxirida to'xtash" },
                    { "AppearanceSection", "Ko'rinish" },
                    { "FontFamilyLabel", "Shrift" },
                    { "FontSizeLabel", "Shrift o'lchami" },
                    { "OverlayWidthLabel", "Overlay kengligi" },
                    { "OverlayHeightLabel", "Overlay balandligi" },
                    { "DisplaySection", "Ekran" },
                    { "ShowOverlayOnLabel", "Overlay qaysi ekranda" },
                    { "ScreenAutoPrimary", "Avto (asosiy ekran)" },
                    { "ScreenPrimarySuffix", "Asosiy" },
                    { "PrivacySection", "Maxfiylik" },
                    { "ShowOverlay", "Overlayni ko'rsatish" },
                    { "LimitScreenSharingCapture", "Ekran ulashda ko'rinishni cheklash" },
                    { "PrivacyNote", "Imkon qadar ishlaydi. Yozib olish holati Windows versiyasi va yozuvchi ilovaga bog'liq." },
                    { "ShortcutsSection", "Tezkor tugmalar" },
                    { "HotkeyHelp", "Hotkey yordam" },
                    { "ResetDefaults", "Standartga qaytarish" },
                    { "HotkeyPressNew", "Yangi tugmalarni bosing. Esc bekor qiladi, Backspace tozalaydi." },
                    { "HotkeyCleared", "Tugma birikmasi tozalandi." },
                    { "HotkeyUseModifier", "Kamida bitta modifier ishlating: Ctrl, Alt, Shift yoki Win." },
                    { "HotkeyAlreadyAssigned", "Bu tugma birikmasi allaqachon berilgan." },
                    { "HotkeyUpdated", "Tugma birikmasi yangilandi." },
                    { "HotkeyPressKeys", "Tugmalarni bosing..." },
                    { "HotkeyDefaultsRestored", "Standart hotkeylar tiklandi." },
                    { "ImportFailedTitle", "Import bajarilmadi" },
                    { "ExportFailedTitle", "Eksport bajarilmadi" },
                    { "ScriptDefault", "Matnni shu yerga qo'ying.\r\n\r\nMaslahat: boshlash/pauza yoki prokrutkani reset qilish uchun tray ikonkasidan foydalaning." },
                    { "FontAppleDefault", "Apple / SF Pro (standart)" },
                    { "Start", "Start" },
                    { "Pause", "Pauza" },
                    { "StartPause", "Start / Pauza" },
                    { "ResetScroll", "Prokrutkani reset qilish" },
                    { "JumpBack5s", "5 soniya orqaga" },
                    { "TogglePrivacyMode", "Maxfiylik rejimini almashtirish" },
                    { "ToggleOverlayVisibility", "Overlayni ko'rsatish/yashirish" },
                    { "IncreaseSpeed", "Tezlikni oshirish" },
                    { "DecreaseSpeed", "Tezlikni kamaytirish" },
                    { "IncreaseFontSize", "Shriftni kattalashtirish" },
                    { "DecreaseFontSize", "Shriftni kichraytirish" },
                    { "PrivacyMode", "Maxfiylik rejimi" },
                    { "ShowOverlayMenu", "Overlayni ko'rsatish" },
                    { "SettingsMenu", "Sozlamalar..." },
                    { "QuitPromptBar", "PromptBardan chiqish" },
                    { "ShortcutUnavailable", "Hotkey ishlamaydi" },
                    { "ShortcutsUnavailable", "Hotkeylar ishlamaydi" },
                    { "HotkeyDialogTitle", "PromptBar hotkeylari" },
                    { "HotkeyUnassigned", "Belgilanmagan" },
                    { "TextEditingShortcutsHeader", "Matnni tahrirlash" },
                    { "SelectAll", "Hammasini tanlash" },
                    { "NoScriptMessage", "Matn hali yo'q.\r\nSozlamalarni ochib matn qo'ying." },
                    { "ReadyMessage", "Suflyor tayyor.\r\nBoshlash uchun Start bosing." },
                    { "OverlayResize", "Overlay o'lchamini o'zgartirish" },
                    { "OverlaySettings", "Sozlamalar" },
                    { "OverlayHotkeyHelp", "Hotkey yordam" },
                    { "OverlayPaste", "Buferdan matn qo'yish" },
                    { "OverlayCopy", "Matnni buferga nusxalash" },
                    { "OverlayClear", "Matnni tozalash" },
                    { "OverlayQuit", "PromptBardan chiqish" }
                }
            },
            { "es", new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
                {
                    { "SettingsWindowTitle", "Configuración de PromptBar" },
                    { "SettingsHeader", "Configuración" },
                    { "GeneralSection", "General" },
                    { "LanguageLabel", "Idioma" },
                    { "ScriptSection", "Texto" },
                    { "Import", "Importar" },
                    { "Export", "Exportar" },
                    { "Copy", "Copiar" },
                    { "Paste", "Pegar" },
                    { "PlaybackSection", "Lectura" },
                    { "SpeedLabel", "Velocidad" },
                    { "ScrollModeLabel", "Modo de desplazamiento" },
                    { "ScrollInfinite", "Infinito" },
                    { "ScrollStopAtEnd", "Detener al final" },
                    { "AppearanceSection", "Apariencia" },
                    { "FontFamilyLabel", "Fuente" },
                    { "FontSizeLabel", "Tamaño de fuente" },
                    { "OverlayWidthLabel", "Ancho del overlay" },
                    { "OverlayHeightLabel", "Alto del overlay" },
                    { "DisplaySection", "Pantalla" },
                    { "ShowOverlayOnLabel", "Mostrar overlay en" },
                    { "ScreenAutoPrimary", "Auto (pantalla principal)" },
                    { "ScreenPrimarySuffix", "Principal" },
                    { "PrivacySection", "Privacidad" },
                    { "ShowOverlay", "Mostrar overlay" },
                    { "LimitScreenSharingCapture", "Limitar captura al compartir pantalla" },
                    { "PrivacyNote", "Es una protección de mejor esfuerzo. La captura puede variar según Windows y la app de grabación." },
                    { "ShortcutsSection", "Atajos de teclado" },
                    { "HotkeyHelp", "Ayuda de atajos" },
                    { "ResetDefaults", "Restablecer" },
                    { "HotkeyPressNew", "Pulsa un nuevo atajo. Esc cancela, Backspace borra." },
                    { "HotkeyCleared", "Atajo borrado." },
                    { "HotkeyUseModifier", "Usa al menos un modificador: Ctrl, Alt, Shift o Win." },
                    { "HotkeyAlreadyAssigned", "Ese atajo ya está asignado." },
                    { "HotkeyUpdated", "Atajo actualizado." },
                    { "HotkeyPressKeys", "Pulsa teclas..." },
                    { "HotkeyDefaultsRestored", "Atajos predeterminados restaurados." },
                    { "ImportFailedTitle", "Error al importar" },
                    { "ExportFailedTitle", "Error al exportar" },
                    { "ScriptDefault", "Pega tu texto aquí.\r\n\r\nConsejo: usa el icono de la bandeja para iniciar, pausar o reiniciar el desplazamiento." },
                    { "FontAppleDefault", "Apple / SF Pro (predeterminado)" },
                    { "Start", "Iniciar" },
                    { "Pause", "Pausar" },
                    { "StartPause", "Iniciar / Pausar" },
                    { "ResetScroll", "Reiniciar desplazamiento" },
                    { "JumpBack5s", "Retroceder 5 segundos" },
                    { "TogglePrivacyMode", "Activar/desactivar privacidad" },
                    { "ToggleOverlayVisibility", "Mostrar/ocultar overlay" },
                    { "IncreaseSpeed", "Aumentar velocidad" },
                    { "DecreaseSpeed", "Reducir velocidad" },
                    { "IncreaseFontSize", "Aumentar fuente" },
                    { "DecreaseFontSize", "Reducir fuente" },
                    { "PrivacyMode", "Modo privacidad" },
                    { "ShowOverlayMenu", "Mostrar overlay" },
                    { "SettingsMenu", "Configuración..." },
                    { "QuitPromptBar", "Salir de PromptBar" },
                    { "ShortcutUnavailable", "Atajo no disponible" },
                    { "ShortcutsUnavailable", "Atajos no disponibles" },
                    { "HotkeyDialogTitle", "Atajos de PromptBar" },
                    { "HotkeyUnassigned", "Sin asignar" },
                    { "TextEditingShortcutsHeader", "Edición de texto" },
                    { "SelectAll", "Seleccionar todo" },
                    { "NoScriptMessage", "Aún no hay texto.\r\nAbre Configuración y pega tu texto." },
                    { "ReadyMessage", "Listo para leer.\r\nPulsa Iniciar para empezar." },
                    { "OverlayResize", "Cambiar tamaño del overlay" },
                    { "OverlaySettings", "Configuración" },
                    { "OverlayHotkeyHelp", "Ayuda de atajos" },
                    { "OverlayPaste", "Pegar texto del portapapeles" },
                    { "OverlayCopy", "Copiar texto al portapapeles" },
                    { "OverlayClear", "Borrar texto" },
                    { "OverlayQuit", "Salir de PromptBar" }
                }
            },
            { "it", new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
                {
                    { "SettingsWindowTitle", "Impostazioni PromptBar" },
                    { "SettingsHeader", "Impostazioni" },
                    { "GeneralSection", "Generale" },
                    { "LanguageLabel", "Lingua" },
                    { "ScriptSection", "Testo" },
                    { "Import", "Importa" },
                    { "Export", "Esporta" },
                    { "Copy", "Copia" },
                    { "Paste", "Incolla" },
                    { "PlaybackSection", "Lettura" },
                    { "SpeedLabel", "Velocità" },
                    { "ScrollModeLabel", "Modalità scorrimento" },
                    { "ScrollInfinite", "Infinito" },
                    { "ScrollStopAtEnd", "Ferma alla fine" },
                    { "AppearanceSection", "Aspetto" },
                    { "FontFamilyLabel", "Font" },
                    { "FontSizeLabel", "Dimensione font" },
                    { "OverlayWidthLabel", "Larghezza overlay" },
                    { "OverlayHeightLabel", "Altezza overlay" },
                    { "DisplaySection", "Schermo" },
                    { "ShowOverlayOnLabel", "Mostra overlay su" },
                    { "ScreenAutoPrimary", "Auto (schermo principale)" },
                    { "ScreenPrimarySuffix", "Principale" },
                    { "PrivacySection", "Privacy" },
                    { "ShowOverlay", "Mostra overlay" },
                    { "LimitScreenSharingCapture", "Limita la cattura durante la condivisione" },
                    { "PrivacyNote", "Funziona al meglio possibile. La cattura può variare in base a Windows e all'app di registrazione." },
                    { "ShortcutsSection", "Scorciatoie da tastiera" },
                    { "HotkeyHelp", "Aiuto scorciatoie" },
                    { "ResetDefaults", "Ripristina" },
                    { "HotkeyPressNew", "Premi una nuova scorciatoia. Esc annulla, Backspace cancella." },
                    { "HotkeyCleared", "Scorciatoia cancellata." },
                    { "HotkeyUseModifier", "Usa almeno un modificatore: Ctrl, Alt, Shift o Win." },
                    { "HotkeyAlreadyAssigned", "Questa scorciatoia è già assegnata." },
                    { "HotkeyUpdated", "Scorciatoia aggiornata." },
                    { "HotkeyPressKeys", "Premi i tasti..." },
                    { "HotkeyDefaultsRestored", "Scorciatoie predefinite ripristinate." },
                    { "ImportFailedTitle", "Importazione non riuscita" },
                    { "ExportFailedTitle", "Esportazione non riuscita" },
                    { "ScriptDefault", "Incolla qui il testo.\r\n\r\nSuggerimento: usa l'icona nella tray per avviare, mettere in pausa o azzerare lo scorrimento." },
                    { "FontAppleDefault", "Apple / SF Pro (predefinito)" },
                    { "Start", "Avvia" },
                    { "Pause", "Pausa" },
                    { "StartPause", "Avvia / Pausa" },
                    { "ResetScroll", "Azzera scorrimento" },
                    { "JumpBack5s", "Indietro di 5 secondi" },
                    { "TogglePrivacyMode", "Attiva/disattiva privacy" },
                    { "ToggleOverlayVisibility", "Mostra/nascondi overlay" },
                    { "IncreaseSpeed", "Aumenta velocità" },
                    { "DecreaseSpeed", "Riduci velocità" },
                    { "IncreaseFontSize", "Aumenta font" },
                    { "DecreaseFontSize", "Riduci font" },
                    { "PrivacyMode", "Modalità privacy" },
                    { "ShowOverlayMenu", "Mostra overlay" },
                    { "SettingsMenu", "Impostazioni..." },
                    { "QuitPromptBar", "Esci da PromptBar" },
                    { "ShortcutUnavailable", "Scorciatoia non disponibile" },
                    { "ShortcutsUnavailable", "Scorciatoie non disponibili" },
                    { "HotkeyDialogTitle", "Scorciatoie PromptBar" },
                    { "HotkeyUnassigned", "Non assegnata" },
                    { "TextEditingShortcutsHeader", "Modifica testo" },
                    { "SelectAll", "Seleziona tutto" },
                    { "NoScriptMessage", "Non c'è ancora testo.\r\nApri Impostazioni e incolla il testo." },
                    { "ReadyMessage", "Pronto per leggere.\r\nPremi Avvia per iniziare." },
                    { "OverlayResize", "Ridimensiona overlay" },
                    { "OverlaySettings", "Impostazioni" },
                    { "OverlayHotkeyHelp", "Aiuto scorciatoie" },
                    { "OverlayPaste", "Incolla testo dagli appunti" },
                    { "OverlayCopy", "Copia testo negli appunti" },
                    { "OverlayClear", "Cancella testo" },
                    { "OverlayQuit", "Esci da PromptBar" }
                }
            },
            { "fr", new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
                {
                    { "SettingsWindowTitle", "Réglages PromptBar" },
                    { "SettingsHeader", "Réglages" },
                    { "GeneralSection", "Général" },
                    { "LanguageLabel", "Langue" },
                    { "ScriptSection", "Texte" },
                    { "Import", "Importer" },
                    { "Export", "Exporter" },
                    { "Copy", "Copier" },
                    { "Paste", "Coller" },
                    { "PlaybackSection", "Lecture" },
                    { "SpeedLabel", "Vitesse" },
                    { "ScrollModeLabel", "Mode de défilement" },
                    { "ScrollInfinite", "Infini" },
                    { "ScrollStopAtEnd", "Arrêter à la fin" },
                    { "AppearanceSection", "Apparence" },
                    { "FontFamilyLabel", "Police" },
                    { "FontSizeLabel", "Taille de police" },
                    { "OverlayWidthLabel", "Largeur de l'overlay" },
                    { "OverlayHeightLabel", "Hauteur de l'overlay" },
                    { "DisplaySection", "Écran" },
                    { "ShowOverlayOnLabel", "Afficher l'overlay sur" },
                    { "ScreenAutoPrimary", "Auto (écran principal)" },
                    { "ScreenPrimarySuffix", "Principal" },
                    { "PrivacySection", "Confidentialité" },
                    { "ShowOverlay", "Afficher l'overlay" },
                    { "LimitScreenSharingCapture", "Limiter la capture en partage d'écran" },
                    { "PrivacyNote", "Protection au mieux. La capture peut varier selon Windows et l'application d'enregistrement." },
                    { "ShortcutsSection", "Raccourcis clavier" },
                    { "HotkeyHelp", "Aide des raccourcis" },
                    { "ResetDefaults", "Réinitialiser" },
                    { "HotkeyPressNew", "Appuyez sur un nouveau raccourci. Esc annule, Backspace efface." },
                    { "HotkeyCleared", "Raccourci effacé." },
                    { "HotkeyUseModifier", "Utilisez au moins un modificateur : Ctrl, Alt, Shift ou Win." },
                    { "HotkeyAlreadyAssigned", "Ce raccourci est déjà attribué." },
                    { "HotkeyUpdated", "Raccourci mis à jour." },
                    { "HotkeyPressKeys", "Appuyez sur les touches..." },
                    { "HotkeyDefaultsRestored", "Raccourcis par défaut restaurés." },
                    { "ImportFailedTitle", "Échec de l'import" },
                    { "ExportFailedTitle", "Échec de l'export" },
                    { "ScriptDefault", "Collez votre texte ici.\r\n\r\nAstuce : utilisez l'icône de la zone de notification pour lancer, mettre en pause ou réinitialiser le défilement." },
                    { "FontAppleDefault", "Apple / SF Pro (par défaut)" },
                    { "Start", "Démarrer" },
                    { "Pause", "Pause" },
                    { "StartPause", "Démarrer / Pause" },
                    { "ResetScroll", "Réinitialiser le défilement" },
                    { "JumpBack5s", "Reculer de 5 secondes" },
                    { "TogglePrivacyMode", "Activer/désactiver la confidentialité" },
                    { "ToggleOverlayVisibility", "Afficher/masquer l'overlay" },
                    { "IncreaseSpeed", "Augmenter la vitesse" },
                    { "DecreaseSpeed", "Réduire la vitesse" },
                    { "IncreaseFontSize", "Agrandir la police" },
                    { "DecreaseFontSize", "Réduire la police" },
                    { "PrivacyMode", "Mode confidentialité" },
                    { "ShowOverlayMenu", "Afficher l'overlay" },
                    { "SettingsMenu", "Réglages..." },
                    { "QuitPromptBar", "Quitter PromptBar" },
                    { "ShortcutUnavailable", "Raccourci indisponible" },
                    { "ShortcutsUnavailable", "Raccourcis indisponibles" },
                    { "HotkeyDialogTitle", "Raccourcis PromptBar" },
                    { "HotkeyUnassigned", "Non attribué" },
                    { "TextEditingShortcutsHeader", "Édition du texte" },
                    { "SelectAll", "Tout sélectionner" },
                    { "NoScriptMessage", "Aucun texte pour le moment.\r\nOuvrez les réglages et collez votre texte." },
                    { "ReadyMessage", "Prêt à lire.\r\nAppuyez sur Démarrer pour commencer." },
                    { "OverlayResize", "Redimensionner l'overlay" },
                    { "OverlaySettings", "Réglages" },
                    { "OverlayHotkeyHelp", "Aide des raccourcis" },
                    { "OverlayPaste", "Coller le texte du presse-papiers" },
                    { "OverlayCopy", "Copier le texte dans le presse-papiers" },
                    { "OverlayClear", "Effacer le texte" },
                    { "OverlayQuit", "Quitter PromptBar" }
                }
            },
            { "pt", new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
                {
                    { "SettingsWindowTitle", "Configurações do PromptBar" },
                    { "SettingsHeader", "Configurações" },
                    { "GeneralSection", "Geral" },
                    { "LanguageLabel", "Idioma" },
                    { "ScriptSection", "Texto" },
                    { "Import", "Importar" },
                    { "Export", "Exportar" },
                    { "Copy", "Copiar" },
                    { "Paste", "Colar" },
                    { "PlaybackSection", "Leitura" },
                    { "SpeedLabel", "Velocidade" },
                    { "ScrollModeLabel", "Modo de rolagem" },
                    { "ScrollInfinite", "Infinito" },
                    { "ScrollStopAtEnd", "Parar no final" },
                    { "AppearanceSection", "Aparência" },
                    { "FontFamilyLabel", "Fonte" },
                    { "FontSizeLabel", "Tamanho da fonte" },
                    { "OverlayWidthLabel", "Largura do overlay" },
                    { "OverlayHeightLabel", "Altura do overlay" },
                    { "DisplaySection", "Tela" },
                    { "ShowOverlayOnLabel", "Mostrar overlay em" },
                    { "ScreenAutoPrimary", "Auto (tela principal)" },
                    { "ScreenPrimarySuffix", "Principal" },
                    { "PrivacySection", "Privacidade" },
                    { "ShowOverlay", "Mostrar overlay" },
                    { "LimitScreenSharingCapture", "Limitar captura no compartilhamento de tela" },
                    { "PrivacyNote", "Proteção de melhor esforço. A captura pode variar conforme o Windows e o app de gravação." },
                    { "ShortcutsSection", "Atalhos de teclado" },
                    { "HotkeyHelp", "Ajuda dos atalhos" },
                    { "ResetDefaults", "Restaurar" },
                    { "HotkeyPressNew", "Pressione um novo atalho. Esc cancela, Backspace limpa." },
                    { "HotkeyCleared", "Atalho limpo." },
                    { "HotkeyUseModifier", "Use pelo menos um modificador: Ctrl, Alt, Shift ou Win." },
                    { "HotkeyAlreadyAssigned", "Esse atalho já está atribuído." },
                    { "HotkeyUpdated", "Atalho atualizado." },
                    { "HotkeyPressKeys", "Pressione as teclas..." },
                    { "HotkeyDefaultsRestored", "Atalhos padrão restaurados." },
                    { "ImportFailedTitle", "Falha ao importar" },
                    { "ExportFailedTitle", "Falha ao exportar" },
                    { "ScriptDefault", "Cole seu texto aqui.\r\n\r\nDica: use o ícone da bandeja para iniciar, pausar ou reiniciar a rolagem." },
                    { "FontAppleDefault", "Apple / SF Pro (padrão)" },
                    { "Start", "Iniciar" },
                    { "Pause", "Pausar" },
                    { "StartPause", "Iniciar / Pausar" },
                    { "ResetScroll", "Reiniciar rolagem" },
                    { "JumpBack5s", "Voltar 5 segundos" },
                    { "TogglePrivacyMode", "Alternar modo de privacidade" },
                    { "ToggleOverlayVisibility", "Mostrar/ocultar overlay" },
                    { "IncreaseSpeed", "Aumentar velocidade" },
                    { "DecreaseSpeed", "Diminuir velocidade" },
                    { "IncreaseFontSize", "Aumentar fonte" },
                    { "DecreaseFontSize", "Diminuir fonte" },
                    { "PrivacyMode", "Modo de privacidade" },
                    { "ShowOverlayMenu", "Mostrar overlay" },
                    { "SettingsMenu", "Configurações..." },
                    { "QuitPromptBar", "Sair do PromptBar" },
                    { "ShortcutUnavailable", "Atalho indisponível" },
                    { "ShortcutsUnavailable", "Atalhos indisponíveis" },
                    { "HotkeyDialogTitle", "Atalhos do PromptBar" },
                    { "HotkeyUnassigned", "Não atribuído" },
                    { "TextEditingShortcutsHeader", "Edição de texto" },
                    { "SelectAll", "Selecionar tudo" },
                    { "NoScriptMessage", "Ainda não há texto.\r\nAbra Configurações e cole seu texto." },
                    { "ReadyMessage", "Pronto para leitura.\r\nPressione Iniciar para começar." },
                    { "OverlayResize", "Redimensionar overlay" },
                    { "OverlaySettings", "Configurações" },
                    { "OverlayHotkeyHelp", "Ajuda dos atalhos" },
                    { "OverlayPaste", "Colar texto da área de transferência" },
                    { "OverlayCopy", "Copiar texto para a área de transferência" },
                    { "OverlayClear", "Limpar texto" },
                    { "OverlayQuit", "Sair do PromptBar" }
                }
            },
            { "kaa", new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
                {
                    { "SettingsWindowTitle", "PromptBar sazlamaları" },
                    { "SettingsHeader", "Sazlamalar" },
                    { "GeneralSection", "Ulıwma" },
                    { "LanguageLabel", "Til" },
                    { "ScriptSection", "Mátin" },
                    { "Import", "Import" },
                    { "Export", "Eksport" },
                    { "Copy", "Nusqalaw" },
                    { "Paste", "Qoyıw" },
                    { "PlaybackSection", "Suflyor" },
                    { "SpeedLabel", "Tezlik" },
                    { "ScrollModeLabel", "Aylantırıw rejimi" },
                    { "ScrollInfinite", "Sheksiz" },
                    { "ScrollStopAtEnd", "Aqırında toqtaw" },
                    { "AppearanceSection", "Kórinis" },
                    { "FontFamilyLabel", "Shrift" },
                    { "FontSizeLabel", "Shrift ólshemi" },
                    { "OverlayWidthLabel", "Overlay eni" },
                    { "OverlayHeightLabel", "Overlay biyikligi" },
                    { "DisplaySection", "Ekran" },
                    { "ShowOverlayOnLabel", "Overlaydi qaysı ekranda kórsetiw" },
                    { "ScreenAutoPrimary", "Avto (tiykarǵı ekran)" },
                    { "ScreenPrimarySuffix", "Tiykarǵı" },
                    { "PrivacySection", "Qupiyalıq" },
                    { "ShowOverlay", "Overlaydi kórsetiw" },
                    { "LimitScreenSharingCapture", "Ekran bóleskende kóriniwin sheklew" },
                    { "PrivacyNote", "Múmkin bolǵanınsha qorǵaydı. Jazıp alıw Windows núsqasına hám qollanbaǵa baylanıslı ózgeriwi múmkin." },
                    { "ShortcutsSection", "Tez túymeler" },
                    { "HotkeyHelp", "Hotkey járdemi" },
                    { "ResetDefaults", "Ádepki halǵa qaytarıw" },
                    { "HotkeyPressNew", "Jańa túymelerdi basıń. Esc biykarlaydı, Backspace tazalaydı." },
                    { "HotkeyCleared", "Túyme birikpesi tazalandı." },
                    { "HotkeyUseModifier", "Keminde bir modifier paydalanıń: Ctrl, Alt, Shift yamasa Win." },
                    { "HotkeyAlreadyAssigned", "Bul túyme birikpesi aldınnan berilgen." },
                    { "HotkeyUpdated", "Túyme birikpesi jańalandı." },
                    { "HotkeyPressKeys", "Túymelerdi basıń..." },
                    { "HotkeyDefaultsRestored", "Ádepki hotkeyler qaytarıldı." },
                    { "ImportFailedTitle", "Import ámelge aspadi" },
                    { "ExportFailedTitle", "Eksport ámelge aspadi" },
                    { "ScriptDefault", "Mátindi bul jerge qoyıń.\r\n\r\nKeńes: baslaw/pauza yamasa aylantırıwdı reset qılıw ushın tray belgisin paydalanıń." },
                    { "FontAppleDefault", "Apple / SF Pro (ádepki)" },
                    { "Start", "Baslaw" },
                    { "Pause", "Pauza" },
                    { "StartPause", "Baslaw / Pauza" },
                    { "ResetScroll", "Aylantırıwdı reset qılıw" },
                    { "JumpBack5s", "5 sekund artqa" },
                    { "TogglePrivacyMode", "Qupiyalıq rejimin almastırıw" },
                    { "ToggleOverlayVisibility", "Overlaydi kórsetiw/jasırıw" },
                    { "IncreaseSpeed", "Tezlikti asırıw" },
                    { "DecreaseSpeed", "Tezlikti azaytıw" },
                    { "IncreaseFontSize", "Shriftti úlkeytiw" },
                    { "DecreaseFontSize", "Shriftti kishireytiw" },
                    { "PrivacyMode", "Qupiyalıq rejimi" },
                    { "ShowOverlayMenu", "Overlaydi kórsetiw" },
                    { "SettingsMenu", "Sazlamalar..." },
                    { "QuitPromptBar", "PromptBartan shıǵıw" },
                    { "ShortcutUnavailable", "Hotkey islemeydi" },
                    { "ShortcutsUnavailable", "Hotkeyler islemeydi" },
                    { "HotkeyDialogTitle", "PromptBar hotkeyleri" },
                    { "HotkeyUnassigned", "Belgilenbegen" },
                    { "TextEditingShortcutsHeader", "Mátindi ózgertiw" },
                    { "SelectAll", "Hámmesin tańlaw" },
                    { "NoScriptMessage", "Mátin ele joq.\r\nSazlamalardı ashıp mátin qoyıń." },
                    { "ReadyMessage", "Suflyor tayar.\r\nBaslaw ushın Start basıń." },
                    { "OverlayResize", "Overlay ólshemin ózgertiw" },
                    { "OverlaySettings", "Sazlamalar" },
                    { "OverlayHotkeyHelp", "Hotkey járdemi" },
                    { "OverlayPaste", "Buferden mátin qoyıw" },
                    { "OverlayCopy", "Mátindi buferge nusqalaw" },
                    { "OverlayClear", "Mátindi tazalaw" },
                    { "OverlayQuit", "PromptBartan shıǵıw" }
                }
            },
            { "tg", new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
                {
                    { "SettingsWindowTitle", "Танзимоти PromptBar" },
                    { "SettingsHeader", "Танзимот" },
                    { "GeneralSection", "Умумӣ" },
                    { "LanguageLabel", "Забон" },
                    { "ScriptSection", "Матн" },
                    { "Import", "Ворид кардан" },
                    { "Export", "Содир кардан" },
                    { "Copy", "Нусха" },
                    { "Paste", "Гузоштан" },
                    { "PlaybackSection", "Суфлёр" },
                    { "SpeedLabel", "Суръат" },
                    { "ScrollModeLabel", "Ҳолати ҳаракат" },
                    { "ScrollInfinite", "Беохир" },
                    { "ScrollStopAtEnd", "Дар охир истодан" },
                    { "AppearanceSection", "Намуди зоҳирӣ" },
                    { "FontFamilyLabel", "Шрифт" },
                    { "FontSizeLabel", "Андозаи шрифт" },
                    { "OverlayWidthLabel", "Паҳноии overlay" },
                    { "OverlayHeightLabel", "Баландии overlay" },
                    { "DisplaySection", "Экран" },
                    { "ShowOverlayOnLabel", "Overlay дар кадом экран" },
                    { "ScreenAutoPrimary", "Авто (экрани асосӣ)" },
                    { "ScreenPrimarySuffix", "Асосӣ" },
                    { "PrivacySection", "Махфият" },
                    { "ShowOverlay", "Намоиши overlay" },
                    { "LimitScreenSharingCapture", "Маҳдуд кардани сабт ҳангоми мубодилаи экран" },
                    { "PrivacyNote", "То ҳадди имкон кор мекунад. Сабт вобаста ба версияи Windows ва барномаи сабт фарқ карда метавонад." },
                    { "ShortcutsSection", "Тугмаҳои зуд" },
                    { "HotkeyHelp", "Ёрии hotkey" },
                    { "ResetDefaults", "Барқарор кардан" },
                    { "HotkeyPressNew", "Комбинатсияи навро пахш кунед. Esc бекор мекунад, Backspace пок мекунад." },
                    { "HotkeyCleared", "Комбинатсия пок шуд." },
                    { "HotkeyUseModifier", "Ҳадди ақал як modifier истифода баред: Ctrl, Alt, Shift ё Win." },
                    { "HotkeyAlreadyAssigned", "Ин комбинатсия аллакай таъин шудааст." },
                    { "HotkeyUpdated", "Комбинатсия нав шуд." },
                    { "HotkeyPressKeys", "Тугмаҳоро пахш кунед..." },
                    { "HotkeyDefaultsRestored", "Hotkey-ҳои пешфарз барқарор шуданд." },
                    { "ImportFailedTitle", "Воридкунӣ ноком шуд" },
                    { "ExportFailedTitle", "Содиркунӣ ноком шуд" },
                    { "ScriptDefault", "Матнро дар ин ҷо гузоред.\r\n\r\nМаслиҳат: барои оғоз, таваққуф ё reset аз нишонаи tray истифода баред." },
                    { "FontAppleDefault", "Apple / SF Pro (пешфарз)" },
                    { "Start", "Оғоз" },
                    { "Pause", "Таваққуф" },
                    { "StartPause", "Оғоз / Таваққуф" },
                    { "ResetScroll", "Reset ҳаракат" },
                    { "JumpBack5s", "5 сония ақиб" },
                    { "TogglePrivacyMode", "Иваз кардани ҳолати махфият" },
                    { "ToggleOverlayVisibility", "Намоиш/пинҳон кардани overlay" },
                    { "IncreaseSpeed", "Зиёд кардани суръат" },
                    { "DecreaseSpeed", "Кам кардани суръат" },
                    { "IncreaseFontSize", "Калон кардани шрифт" },
                    { "DecreaseFontSize", "Хурд кардани шрифт" },
                    { "PrivacyMode", "Ҳолати махфият" },
                    { "ShowOverlayMenu", "Намоиши overlay" },
                    { "SettingsMenu", "Танзимот..." },
                    { "QuitPromptBar", "Баромадан аз PromptBar" },
                    { "ShortcutUnavailable", "Hotkey дастнорас аст" },
                    { "ShortcutsUnavailable", "Hotkey-ҳо дастнорасанд" },
                    { "HotkeyDialogTitle", "Hotkey-ҳои PromptBar" },
                    { "HotkeyUnassigned", "Таъин нашудааст" },
                    { "TextEditingShortcutsHeader", "Таҳрири матн" },
                    { "SelectAll", "Ҳамаро интихоб кардан" },
                    { "NoScriptMessage", "Ҳоло матн нест.\r\nТанзимотро кушоед ва матнро гузоред." },
                    { "ReadyMessage", "Суфлёр омода аст.\r\nБарои оғоз Оғозро пахш кунед." },
                    { "OverlayResize", "Тағйири андозаи overlay" },
                    { "OverlaySettings", "Танзимот" },
                    { "OverlayHotkeyHelp", "Ёрии hotkey" },
                    { "OverlayPaste", "Гузоштани матн аз буфер" },
                    { "OverlayCopy", "Нусхабардории матн ба буфер" },
                    { "OverlayClear", "Пок кардани матн" },
                    { "OverlayQuit", "Баромадан аз PromptBar" }
                }
            },
            { "kk", new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
                {
                    { "SettingsWindowTitle", "PromptBar баптаулары" },
                    { "SettingsHeader", "Баптаулар" },
                    { "GeneralSection", "Жалпы" },
                    { "LanguageLabel", "Тіл" },
                    { "ScriptSection", "Мәтін" },
                    { "Import", "Импорт" },
                    { "Export", "Экспорт" },
                    { "Copy", "Көшіру" },
                    { "Paste", "Қою" },
                    { "PlaybackSection", "Суфлер" },
                    { "SpeedLabel", "Жылдамдық" },
                    { "ScrollModeLabel", "Айналдыру режимі" },
                    { "ScrollInfinite", "Шексіз" },
                    { "ScrollStopAtEnd", "Соңында тоқтау" },
                    { "AppearanceSection", "Көрініс" },
                    { "FontFamilyLabel", "Қаріп" },
                    { "FontSizeLabel", "Қаріп өлшемі" },
                    { "OverlayWidthLabel", "Overlay ені" },
                    { "OverlayHeightLabel", "Overlay биіктігі" },
                    { "DisplaySection", "Экран" },
                    { "ShowOverlayOnLabel", "Overlay қай экранда көрсетіледі" },
                    { "ScreenAutoPrimary", "Авто (негізгі экран)" },
                    { "ScreenPrimarySuffix", "Негізгі" },
                    { "PrivacySection", "Құпиялылық" },
                    { "ShowOverlay", "Overlay көрсету" },
                    { "LimitScreenSharingCapture", "Экран бөліскенде түсіруді шектеу" },
                    { "PrivacyNote", "Мүмкіндігінше қорғайды. Түсіру Windows нұсқасына және жазу қолданбасына байланысты өзгеруі мүмкін." },
                    { "ShortcutsSection", "Жылдам пернелер" },
                    { "HotkeyHelp", "Hotkey анықтамасы" },
                    { "ResetDefaults", "Әдепкіге қайтару" },
                    { "HotkeyPressNew", "Жаңа пернелер тіркесімін басыңыз. Esc болдырмайды, Backspace тазартады." },
                    { "HotkeyCleared", "Пернелер тіркесімі тазартылды." },
                    { "HotkeyUseModifier", "Кемінде бір modifier қолданыңыз: Ctrl, Alt, Shift немесе Win." },
                    { "HotkeyAlreadyAssigned", "Бұл тіркесім бұрыннан тағайындалған." },
                    { "HotkeyUpdated", "Пернелер тіркесімі жаңартылды." },
                    { "HotkeyPressKeys", "Пернелерді басыңыз..." },
                    { "HotkeyDefaultsRestored", "Әдепкі hotkey-лер қалпына келтірілді." },
                    { "ImportFailedTitle", "Импорт сәтсіз аяқталды" },
                    { "ExportFailedTitle", "Экспорт сәтсіз аяқталды" },
                    { "ScriptDefault", "Мәтінді осы жерге қойыңыз.\r\n\r\nКеңес: бастау/кідірту немесе айналдыруды reset жасау үшін tray белгішесін пайдаланыңыз." },
                    { "FontAppleDefault", "Apple / SF Pro (әдепкі)" },
                    { "Start", "Бастау" },
                    { "Pause", "Кідірту" },
                    { "StartPause", "Бастау / Кідірту" },
                    { "ResetScroll", "Айналдыруды reset жасау" },
                    { "JumpBack5s", "5 секунд артқа" },
                    { "TogglePrivacyMode", "Құпиялылық режимін ауыстыру" },
                    { "ToggleOverlayVisibility", "Overlay көрсету/жасыру" },
                    { "IncreaseSpeed", "Жылдамдықты арттыру" },
                    { "DecreaseSpeed", "Жылдамдықты азайту" },
                    { "IncreaseFontSize", "Қаріпті үлкейту" },
                    { "DecreaseFontSize", "Қаріпті кішірейту" },
                    { "PrivacyMode", "Құпиялылық режимі" },
                    { "ShowOverlayMenu", "Overlay көрсету" },
                    { "SettingsMenu", "Баптаулар..." },
                    { "QuitPromptBar", "PromptBar-тан шығу" },
                    { "ShortcutUnavailable", "Hotkey қолжетімсіз" },
                    { "ShortcutsUnavailable", "Hotkey-лер қолжетімсіз" },
                    { "HotkeyDialogTitle", "PromptBar hotkey-лері" },
                    { "HotkeyUnassigned", "Тағайындалмаған" },
                    { "TextEditingShortcutsHeader", "Мәтінді өңдеу" },
                    { "SelectAll", "Барлығын таңдау" },
                    { "NoScriptMessage", "Әзірге мәтін жоқ.\r\nБаптауларды ашып, мәтінді қойыңыз." },
                    { "ReadyMessage", "Суфлер дайын.\r\nБастау үшін Бастау түймесін басыңыз." },
                    { "OverlayResize", "Overlay өлшемін өзгерту" },
                    { "OverlaySettings", "Баптаулар" },
                    { "OverlayHotkeyHelp", "Hotkey анықтамасы" },
                    { "OverlayPaste", "Буферден мәтін қою" },
                    { "OverlayCopy", "Мәтінді буферге көшіру" },
                    { "OverlayClear", "Мәтінді тазарту" },
                    { "OverlayQuit", "PromptBar-тан шығу" }
                }
            },
            { "be", new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
                {
                    { "SettingsWindowTitle", "Налады PromptBar" },
                    { "SettingsHeader", "Налады" },
                    { "GeneralSection", "Агульныя" },
                    { "LanguageLabel", "Мова" },
                    { "ScriptSection", "Тэкст" },
                    { "Import", "Імпарт" },
                    { "Export", "Экспарт" },
                    { "Copy", "Капіяваць" },
                    { "Paste", "Уставіць" },
                    { "PlaybackSection", "Суфлёр" },
                    { "SpeedLabel", "Хуткасць" },
                    { "ScrollModeLabel", "Рэжым пракруткі" },
                    { "ScrollInfinite", "Бясконца" },
                    { "ScrollStopAtEnd", "Спыніць у канцы" },
                    { "AppearanceSection", "Выгляд" },
                    { "FontFamilyLabel", "Шрыфт" },
                    { "FontSizeLabel", "Памер шрыфту" },
                    { "OverlayWidthLabel", "Шырыня overlay" },
                    { "OverlayHeightLabel", "Вышыня overlay" },
                    { "DisplaySection", "Экран" },
                    { "ShowOverlayOnLabel", "Паказваць overlay на" },
                    { "ScreenAutoPrimary", "Аўта (асноўны экран)" },
                    { "ScreenPrimarySuffix", "Асноўны" },
                    { "PrivacySection", "Прыватнасць" },
                    { "ShowOverlay", "Паказваць overlay" },
                    { "LimitScreenSharingCapture", "Абмежаваць захоп пры дэманстрацыі экрана" },
                    { "PrivacyNote", "Працуе па магчымасці. Захоп можа адрознівацца ў розных версіях Windows і праграмах запісу." },
                    { "ShortcutsSection", "Гарачыя клавішы" },
                    { "HotkeyHelp", "Дапамога па hotkey" },
                    { "ResetDefaults", "Скінуць" },
                    { "HotkeyPressNew", "Націсніце новае спалучэнне. Esc адмяняе, Backspace ачышчае." },
                    { "HotkeyCleared", "Спалучэнне ачышчана." },
                    { "HotkeyUseModifier", "Выкарыстоўвайце хаця б адзін modifier: Ctrl, Alt, Shift або Win." },
                    { "HotkeyAlreadyAssigned", "Гэта спалучэнне ўжо прызначана." },
                    { "HotkeyUpdated", "Спалучэнне абноўлена." },
                    { "HotkeyPressKeys", "Націсніце клавішы..." },
                    { "HotkeyDefaultsRestored", "Прадвызначаныя hotkey адноўлены." },
                    { "ImportFailedTitle", "Імпарт не ўдаўся" },
                    { "ExportFailedTitle", "Экспарт не ўдаўся" },
                    { "ScriptDefault", "Устаўце тэкст тут.\r\n\r\nПадказка: выкарыстоўвайце значок у tray, каб запусціць, паставіць на паўзу або скінуць пракрутку." },
                    { "FontAppleDefault", "Apple / SF Pro (прадвызначана)" },
                    { "Start", "Старт" },
                    { "Pause", "Паўза" },
                    { "StartPause", "Старт / Паўза" },
                    { "ResetScroll", "Скінуць пракрутку" },
                    { "JumpBack5s", "Назад на 5 секунд" },
                    { "TogglePrivacyMode", "Пераключыць прыватнасць" },
                    { "ToggleOverlayVisibility", "Паказаць/схаваць overlay" },
                    { "IncreaseSpeed", "Павялічыць хуткасць" },
                    { "DecreaseSpeed", "Паменшыць хуткасць" },
                    { "IncreaseFontSize", "Павялічыць шрыфт" },
                    { "DecreaseFontSize", "Паменшыць шрыфт" },
                    { "PrivacyMode", "Рэжым прыватнасці" },
                    { "ShowOverlayMenu", "Паказваць overlay" },
                    { "SettingsMenu", "Налады..." },
                    { "QuitPromptBar", "Выйсці з PromptBar" },
                    { "ShortcutUnavailable", "Hotkey недаступны" },
                    { "ShortcutsUnavailable", "Hotkey недаступныя" },
                    { "HotkeyDialogTitle", "Hotkey PromptBar" },
                    { "HotkeyUnassigned", "Не прызначана" },
                    { "TextEditingShortcutsHeader", "Рэдагаванне тэксту" },
                    { "SelectAll", "Вылучыць усё" },
                    { "NoScriptMessage", "Тэксту пакуль няма.\r\nАдкрыйце налады і ўстаўце тэкст." },
                    { "ReadyMessage", "Суфлёр гатовы.\r\nНацісніце Старт, каб пачаць." },
                    { "OverlayResize", "Змяніць памер overlay" },
                    { "OverlaySettings", "Налады" },
                    { "OverlayHotkeyHelp", "Дапамога па hotkey" },
                    { "OverlayPaste", "Уставіць тэкст з буфера" },
                    { "OverlayCopy", "Капіяваць тэкст у буфер" },
                    { "OverlayClear", "Ачысціць тэкст" },
                    { "OverlayQuit", "Выйсці з PromptBar" }
                }
            },
            { "ja", new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
                {
                    { "SettingsWindowTitle", "PromptBar 設定" },
                    { "SettingsHeader", "設定" },
                    { "GeneralSection", "一般" },
                    { "LanguageLabel", "言語" },
                    { "ScriptSection", "スクリプト" },
                    { "Import", "インポート" },
                    { "Export", "エクスポート" },
                    { "Copy", "コピー" },
                    { "Paste", "貼り付け" },
                    { "PlaybackSection", "再生" },
                    { "SpeedLabel", "速度" },
                    { "ScrollModeLabel", "スクロールモード" },
                    { "ScrollInfinite", "無限" },
                    { "ScrollStopAtEnd", "末尾で停止" },
                    { "AppearanceSection", "外観" },
                    { "FontFamilyLabel", "フォント" },
                    { "FontSizeLabel", "フォントサイズ" },
                    { "OverlayWidthLabel", "オーバーレイ幅" },
                    { "OverlayHeightLabel", "オーバーレイ高さ" },
                    { "DisplaySection", "表示" },
                    { "ShowOverlayOnLabel", "オーバーレイを表示する画面" },
                    { "ScreenAutoPrimary", "自動 (メイン画面)" },
                    { "ScreenPrimarySuffix", "メイン" },
                    { "PrivacySection", "プライバシー" },
                    { "ShowOverlay", "オーバーレイを表示" },
                    { "LimitScreenSharingCapture", "画面共有でのキャプチャを制限" },
                    { "PrivacyNote", "ベストエフォートの保護です。キャプチャ動作は Windows のバージョンや録画アプリによって変わる場合があります。" },
                    { "ShortcutsSection", "キーボードショートカット" },
                    { "HotkeyHelp", "ショートカットヘルプ" },
                    { "ResetDefaults", "既定に戻す" },
                    { "HotkeyPressNew", "新しいショートカットを押してください。Esc でキャンセル、Backspace でクリアします。" },
                    { "HotkeyCleared", "ショートカットをクリアしました。" },
                    { "HotkeyUseModifier", "Ctrl、Alt、Shift、Win のいずれかを含めてください。" },
                    { "HotkeyAlreadyAssigned", "そのショートカットは既に割り当てられています。" },
                    { "HotkeyUpdated", "ショートカットを更新しました。" },
                    { "HotkeyPressKeys", "キーを押してください..." },
                    { "HotkeyDefaultsRestored", "既定のショートカットを復元しました。" },
                    { "ImportFailedTitle", "インポートに失敗しました" },
                    { "ExportFailedTitle", "エクスポートに失敗しました" },
                    { "ScriptDefault", "ここにスクリプトを貼り付けます。\r\n\r\nヒント: トレイアイコンから開始、一時停止、スクロールのリセットができます。" },
                    { "FontAppleDefault", "Apple / SF Pro (既定)" },
                    { "Start", "開始" },
                    { "Pause", "一時停止" },
                    { "StartPause", "開始 / 一時停止" },
                    { "ResetScroll", "スクロールをリセット" },
                    { "JumpBack5s", "5秒戻る" },
                    { "TogglePrivacyMode", "プライバシーモードを切り替え" },
                    { "ToggleOverlayVisibility", "オーバーレイを表示/非表示" },
                    { "IncreaseSpeed", "速度を上げる" },
                    { "DecreaseSpeed", "速度を下げる" },
                    { "IncreaseFontSize", "フォントを大きく" },
                    { "DecreaseFontSize", "フォントを小さく" },
                    { "PrivacyMode", "プライバシーモード" },
                    { "ShowOverlayMenu", "オーバーレイを表示" },
                    { "SettingsMenu", "設定..." },
                    { "QuitPromptBar", "PromptBar を終了" },
                    { "ShortcutUnavailable", "ショートカットを使用できません" },
                    { "ShortcutsUnavailable", "ショートカットを使用できません" },
                    { "HotkeyDialogTitle", "PromptBar ショートカット" },
                    { "HotkeyUnassigned", "未割り当て" },
                    { "TextEditingShortcutsHeader", "テキスト編集" },
                    { "SelectAll", "すべて選択" },
                    { "NoScriptMessage", "スクリプトがまだありません。\r\n設定を開いてテキストを貼り付けてください。" },
                    { "ReadyMessage", "準備完了です。\r\n開始を押すと始まります。" },
                    { "OverlayResize", "オーバーレイのサイズ変更" },
                    { "OverlaySettings", "設定" },
                    { "OverlayHotkeyHelp", "ショートカットヘルプ" },
                    { "OverlayPaste", "クリップボードから貼り付け" },
                    { "OverlayCopy", "クリップボードへコピー" },
                    { "OverlayClear", "テキストをクリア" },
                    { "OverlayQuit", "PromptBar を終了" }
                }
            },
            { "zh", new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
                {
                    { "SettingsWindowTitle", "PromptBar 设置" },
                    { "SettingsHeader", "设置" },
                    { "GeneralSection", "常规" },
                    { "LanguageLabel", "语言" },
                    { "ScriptSection", "文本" },
                    { "Import", "导入" },
                    { "Export", "导出" },
                    { "Copy", "复制" },
                    { "Paste", "粘贴" },
                    { "PlaybackSection", "播放" },
                    { "SpeedLabel", "速度" },
                    { "ScrollModeLabel", "滚动模式" },
                    { "ScrollInfinite", "无限" },
                    { "ScrollStopAtEnd", "到末尾停止" },
                    { "AppearanceSection", "外观" },
                    { "FontFamilyLabel", "字体" },
                    { "FontSizeLabel", "字号" },
                    { "OverlayWidthLabel", "覆盖层宽度" },
                    { "OverlayHeightLabel", "覆盖层高度" },
                    { "DisplaySection", "显示" },
                    { "ShowOverlayOnLabel", "显示覆盖层的屏幕" },
                    { "ScreenAutoPrimary", "自动（主屏幕）" },
                    { "ScreenPrimarySuffix", "主屏幕" },
                    { "PrivacySection", "隐私" },
                    { "ShowOverlay", "显示覆盖层" },
                    { "LimitScreenSharingCapture", "限制屏幕共享捕获" },
                    { "PrivacyNote", "仅尽力保护。捕获行为可能因 Windows 版本和录制应用而异。" },
                    { "ShortcutsSection", "键盘快捷键" },
                    { "HotkeyHelp", "快捷键帮助" },
                    { "ResetDefaults", "恢复默认" },
                    { "HotkeyPressNew", "按下新的快捷键。Esc 取消，Backspace 清除。" },
                    { "HotkeyCleared", "快捷键已清除。" },
                    { "HotkeyUseModifier", "至少使用一个修饰键：Ctrl、Alt、Shift 或 Win。" },
                    { "HotkeyAlreadyAssigned", "该快捷键已被分配。" },
                    { "HotkeyUpdated", "快捷键已更新。" },
                    { "HotkeyPressKeys", "请按键..." },
                    { "HotkeyDefaultsRestored", "默认快捷键已恢复。" },
                    { "ImportFailedTitle", "导入失败" },
                    { "ExportFailedTitle", "导出失败" },
                    { "ScriptDefault", "在此粘贴你的文本。\r\n\r\n提示：可使用托盘图标开始、暂停或重置滚动。" },
                    { "FontAppleDefault", "Apple / SF Pro（默认）" },
                    { "Start", "开始" },
                    { "Pause", "暂停" },
                    { "StartPause", "开始 / 暂停" },
                    { "ResetScroll", "重置滚动" },
                    { "JumpBack5s", "后退 5 秒" },
                    { "TogglePrivacyMode", "切换隐私模式" },
                    { "ToggleOverlayVisibility", "显示/隐藏覆盖层" },
                    { "IncreaseSpeed", "提高速度" },
                    { "DecreaseSpeed", "降低速度" },
                    { "IncreaseFontSize", "增大字体" },
                    { "DecreaseFontSize", "减小字体" },
                    { "PrivacyMode", "隐私模式" },
                    { "ShowOverlayMenu", "显示覆盖层" },
                    { "SettingsMenu", "设置..." },
                    { "QuitPromptBar", "退出 PromptBar" },
                    { "ShortcutUnavailable", "快捷键不可用" },
                    { "ShortcutsUnavailable", "快捷键不可用" },
                    { "HotkeyDialogTitle", "PromptBar 快捷键" },
                    { "HotkeyUnassigned", "未分配" },
                    { "TextEditingShortcutsHeader", "文本编辑" },
                    { "SelectAll", "全选" },
                    { "NoScriptMessage", "还没有文本。\r\n打开设置并粘贴文本。" },
                    { "ReadyMessage", "已准备好提示。\r\n按开始即可开始。" },
                    { "OverlayResize", "调整覆盖层大小" },
                    { "OverlaySettings", "设置" },
                    { "OverlayHotkeyHelp", "快捷键帮助" },
                    { "OverlayPaste", "从剪贴板粘贴文本" },
                    { "OverlayCopy", "复制文本到剪贴板" },
                    { "OverlayClear", "清除文本" },
                    { "OverlayQuit", "退出 PromptBar" }
                }
            },
            { "hi", new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
                {
                    { "SettingsWindowTitle", "PromptBar सेटिंग्स" },
                    { "SettingsHeader", "सेटिंग्स" },
                    { "GeneralSection", "सामान्य" },
                    { "LanguageLabel", "भाषा" },
                    { "ScriptSection", "स्क्रिप्ट" },
                    { "Import", "इम्पोर्ट" },
                    { "Export", "एक्सपोर्ट" },
                    { "Copy", "कॉपी" },
                    { "Paste", "पेस्ट" },
                    { "PlaybackSection", "प्लेबैक" },
                    { "SpeedLabel", "गति" },
                    { "ScrollModeLabel", "स्क्रॉल मोड" },
                    { "ScrollInfinite", "अनंत" },
                    { "ScrollStopAtEnd", "अंत में रोकें" },
                    { "AppearanceSection", "दिखावट" },
                    { "FontFamilyLabel", "फ़ॉन्ट" },
                    { "FontSizeLabel", "फ़ॉन्ट आकार" },
                    { "OverlayWidthLabel", "Overlay चौड़ाई" },
                    { "OverlayHeightLabel", "Overlay ऊँचाई" },
                    { "DisplaySection", "डिस्प्ले" },
                    { "ShowOverlayOnLabel", "Overlay किस स्क्रीन पर दिखाएँ" },
                    { "ScreenAutoPrimary", "ऑटो (मुख्य स्क्रीन)" },
                    { "ScreenPrimarySuffix", "मुख्य" },
                    { "PrivacySection", "गोपनीयता" },
                    { "ShowOverlay", "Overlay दिखाएँ" },
                    { "LimitScreenSharingCapture", "स्क्रीन शेयरिंग कैप्चर सीमित करें" },
                    { "PrivacyNote", "यह best-effort सुरक्षा है। कैप्चर व्यवहार Windows संस्करण और रिकॉर्डिंग ऐप के अनुसार बदल सकता है।" },
                    { "ShortcutsSection", "कीबोर्ड शॉर्टकट" },
                    { "HotkeyHelp", "Hotkey सहायता" },
                    { "ResetDefaults", "डिफ़ॉल्ट रीसेट करें" },
                    { "HotkeyPressNew", "नया शॉर्टकट दबाएँ। Esc रद्द करता है, Backspace साफ करता है।" },
                    { "HotkeyCleared", "शॉर्टकट साफ कर दिया गया।" },
                    { "HotkeyUseModifier", "कम से कम एक modifier उपयोग करें: Ctrl, Alt, Shift या Win." },
                    { "HotkeyAlreadyAssigned", "यह शॉर्टकट पहले से असाइन है।" },
                    { "HotkeyUpdated", "शॉर्टकट अपडेट हुआ।" },
                    { "HotkeyPressKeys", "कुंजियाँ दबाएँ..." },
                    { "HotkeyDefaultsRestored", "डिफ़ॉल्ट hotkey वापस आ गए।" },
                    { "ImportFailedTitle", "इम्पोर्ट विफल" },
                    { "ExportFailedTitle", "एक्सपोर्ट विफल" },
                    { "ScriptDefault", "अपना टेक्स्ट यहाँ पेस्ट करें।\r\n\r\nसुझाव: शुरू, pause या scroll reset करने के लिए tray icon इस्तेमाल करें।" },
                    { "FontAppleDefault", "Apple / SF Pro (डिफ़ॉल्ट)" },
                    { "Start", "शुरू" },
                    { "Pause", "Pause" },
                    { "StartPause", "शुरू / Pause" },
                    { "ResetScroll", "स्क्रॉल reset करें" },
                    { "JumpBack5s", "5 सेकंड पीछे" },
                    { "TogglePrivacyMode", "गोपनीयता मोड बदलें" },
                    { "ToggleOverlayVisibility", "Overlay दिखाएँ/छिपाएँ" },
                    { "IncreaseSpeed", "गति बढ़ाएँ" },
                    { "DecreaseSpeed", "गति घटाएँ" },
                    { "IncreaseFontSize", "फ़ॉन्ट बड़ा करें" },
                    { "DecreaseFontSize", "फ़ॉन्ट छोटा करें" },
                    { "PrivacyMode", "गोपनीयता मोड" },
                    { "ShowOverlayMenu", "Overlay दिखाएँ" },
                    { "SettingsMenu", "सेटिंग्स..." },
                    { "QuitPromptBar", "PromptBar बंद करें" },
                    { "ShortcutUnavailable", "Hotkey उपलब्ध नहीं" },
                    { "ShortcutsUnavailable", "Hotkey उपलब्ध नहीं" },
                    { "HotkeyDialogTitle", "PromptBar hotkey" },
                    { "HotkeyUnassigned", "असाइन नहीं" },
                    { "TextEditingShortcutsHeader", "टेक्स्ट संपादन" },
                    { "SelectAll", "सब चुनें" },
                    { "NoScriptMessage", "अभी कोई टेक्स्ट नहीं है।\r\nसेटिंग्स खोलें और टेक्स्ट पेस्ट करें।" },
                    { "ReadyMessage", "सुफ़्लेर तैयार है।\r\nशुरू करने के लिए शुरू दबाएँ।" },
                    { "OverlayResize", "Overlay आकार बदलें" },
                    { "OverlaySettings", "सेटिंग्स" },
                    { "OverlayHotkeyHelp", "Hotkey सहायता" },
                    { "OverlayPaste", "क्लिपबोर्ड से टेक्स्ट पेस्ट करें" },
                    { "OverlayCopy", "टेक्स्ट क्लिपबोर्ड में कॉपी करें" },
                    { "OverlayClear", "टेक्स्ट साफ करें" },
                    { "OverlayQuit", "PromptBar बंद करें" }
                }
            }
        };

        public static IList<LanguageOption> SupportedLanguages
        {
            get { return Array.AsReadOnly(languages); }
        }

        public static string NormalizeLanguageCode(string code)
        {
            if (String.IsNullOrWhiteSpace(code))
            {
                return DefaultLanguageCode;
            }

            string normalized = code.Trim().ToLowerInvariant();
            for (int i = 0; i < languages.Length; i++)
            {
                if (String.Equals(languages[i].Code, normalized, StringComparison.OrdinalIgnoreCase))
                {
                    return languages[i].Code;
                }
            }

            return DefaultLanguageCode;
        }

        public static string Text(string languageCode, string key)
        {
            string code = NormalizeLanguageCode(languageCode);
            string value;
            Dictionary<string, string> languageTexts;
            if (texts.TryGetValue(code, out languageTexts) && languageTexts.TryGetValue(key, out value))
            {
                return value;
            }

            Dictionary<string, string> fallbackTexts;
            if (texts.TryGetValue(DefaultLanguageCode, out fallbackTexts) && fallbackTexts.TryGetValue(key, out value))
            {
                return value;
            }

            return key;
        }

        public static string CommandText(string languageCode, ShortcutCommand command)
        {
            if (command == ShortcutCommand.StartPause) return Text(languageCode, "StartPause");
            if (command == ShortcutCommand.Reset) return Text(languageCode, "ResetScroll");
            if (command == ShortcutCommand.JumpBack) return Text(languageCode, "JumpBack5s");
            if (command == ShortcutCommand.TogglePrivacy) return Text(languageCode, "TogglePrivacyMode");
            if (command == ShortcutCommand.ToggleOverlay) return Text(languageCode, "ToggleOverlayVisibility");
            if (command == ShortcutCommand.SpeedUp) return Text(languageCode, "IncreaseSpeed");
            if (command == ShortcutCommand.SpeedDown) return Text(languageCode, "DecreaseSpeed");
            if (command == ShortcutCommand.FontSizeUp) return Text(languageCode, "IncreaseFontSize");
            return Text(languageCode, "DecreaseFontSize");
        }
    }
}
